---
# Common defaults for all hosts
ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"

# Packages installed via transactional-update on SUSE hosts.
suse_transactional_packages:
  - bottom
  - python3-selinux
  - neowofetch
  - tmux
