---
- name: Komodo
  hosts: server1
  gather_facts: true
  vars_files:
    - ../group_vars/all.yml
    - ../group_vars/all.vault.yml
  tasks:
    - name: Ensure Komodo home subdir exists
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/komodo"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Deploy Komodo files
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../files/komodo/mongo.compose.yaml"
        dest: "/home/{{ ansible_user }}/komodo/mongo.compose.yaml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

    - name: Render Komodo compose env file
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/komodo/compose.env.j2"
        dest: "/home/{{ ansible_user }}/komodo/compose.env"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"
